2024-10-06 23:14:30,370 - INFO - Finished! Total sfe time: 10.322967529296875 
2024-10-06 23:14:30,370 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', '2024-10-06 22:22:35,297 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 22:22:36,181 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:36,250 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:36,284 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:36,323 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 717 success.', '2024-10-06 22:22:36,367 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:36,372 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 22:22:36,373 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 22:22:36,376 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 22:22:36,377 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 717"', '\tUser time (seconds): 6.41', '\tSystem time (seconds): 0.75', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.10', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 79760', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15899', '\tVoluntary context switches: 51', '\tInvoluntary context switches: 189', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 23:14:30,370 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', '2024-10-06 22:22:34,848 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 22:22:34,908 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 22:22:35,974 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:36,009 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:36,041 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:36,096 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:36,113 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:36,134 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 22:22:36,135 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 22:22:36,138 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 22:22:36,139 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 717"', '\tUser time (seconds): 6.37', '\tSystem time (seconds): 0.77', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.27', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80644', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16022', '\tVoluntary context switches: 54', '\tInvoluntary context switches: 118', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 23:14:30,370 - DEBUG - 717,server, Parsed server ram usage: {'Command being timed': '"python3 server_energy.py 0 717"', 'User time (seconds)': '6.41', 'System time (seconds)': '0.75', 'Percent of CPU this job got': '88%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.10', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '79760', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '15899', 'Voluntary context switches': '51', 'Involuntary context switches': '189', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 23:14:30,370 - DEBUG - 717,client, Parsed client ram usage: {'Command being timed': '"python3 server_energy.py 1 717"', 'User time (seconds)': '6.37', 'System time (seconds)': '0.77', 'Percent of CPU this job got': '86%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.27', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80644', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '16022', 'Voluntary context switches': '54', 'Involuntary context switches': '118', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 23:14:48,864 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 22:22:45,876 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 22:22:46,905 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:46,986 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:47,026 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:47,062 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 717 success.', '2024-10-06 22:22:47,132 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 22:22:47,137 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 22:22:47,138 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 22:22:47,141 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 22:22:47,142 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 717"', '\tUser time (seconds): 6.75', '\tSystem time (seconds): 0.73', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.58', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80396', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15905', '\tVoluntary context switches: 40', '\tInvoluntary context switches: 103', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_23-14-20.csv'], error []
2024-10-06 23:14:48,864 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 22:22:45,539 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 22:22:45,628 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 22:22:46,700 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:46,749 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:46,783 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:46,836 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:46,873 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 22:22:46,899 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 22:22:46,901 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 22:22:46,905 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 22:22:46,906 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 717"', '\tUser time (seconds): 6.83', '\tSystem time (seconds): 0.69', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.73', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80824', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16025', '\tVoluntary context switches: 49', '\tInvoluntary context switches: 199', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_23-14-20.csv'], error []
2024-10-06 23:14:50,216 - DEBUG - All values from powertop for client: 1       519 mW  
25     1.29 mW  
Name: 7, dtype: object
2024-10-06 23:14:50,216 - DEBUG - Energy client: 3.8345373000000005
2024-10-06 23:14:51,534 - DEBUG - All values from powertop for server: 1       548 mW  
20     1.20 mW  
Name: 7, dtype: object
2024-10-06 23:14:51,534 - DEBUG - Energy server: 4.069572
