2024-10-07 01:43:33,893 - INFO - Finished! Total sfe time: 10.434881448745728 
2024-10-07 01:43:33,893 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', '2024-10-07 00:51:38,712 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-07 00:51:39,628 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:39,701 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:39,735 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:39,772 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 996 success.', '2024-10-07 00:51:39,816 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:39,820 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-07 00:51:39,822 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-07 00:51:39,824 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-07 00:51:39,826 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 996"', '\tUser time (seconds): 6.36', '\tSystem time (seconds): 0.74', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.07', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80112', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15903', '\tVoluntary context switches: 51', '\tInvoluntary context switches: 129', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-07 01:43:33,893 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', '2024-10-07 00:51:38,301 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-07 00:51:38,309 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-07 00:51:39,382 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:39,418 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:39,450 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:39,503 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:39,519 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:39,540 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-07 00:51:39,542 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-07 00:51:39,546 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-07 00:51:39,547 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 996"', '\tUser time (seconds): 6.49', '\tSystem time (seconds): 0.66', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.24', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80140', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16017', '\tVoluntary context switches: 55', '\tInvoluntary context switches: 222', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-07 01:43:33,894 - DEBUG - 996,server, Parsed server ram usage: {'Command being timed': '"python3 server_energy.py 0 996"', 'User time (seconds)': '6.36', 'System time (seconds)': '0.74', 'Percent of CPU this job got': '88%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.07', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80112', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '15903', 'Voluntary context switches': '51', 'Involuntary context switches': '129', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-07 01:43:33,894 - DEBUG - 996,client, Parsed client ram usage: {'Command being timed': '"python3 server_energy.py 1 996"', 'User time (seconds)': '6.49', 'System time (seconds)': '0.66', 'Percent of CPU this job got': '86%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.24', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80140', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '16017', 'Voluntary context switches': '55', 'Involuntary context switches': '222', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-07 01:43:59,141 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-07 00:51:49,572 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-07 00:51:50,403 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:50,476 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:50,512 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:50,552 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 996 success.', '2024-10-07 00:51:50,598 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-07 00:51:50,603 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-07 00:51:50,604 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-07 00:51:50,607 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-07 00:51:50,609 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 996"', '\tUser time (seconds): 6.78', '\tSystem time (seconds): 0.73', '\tPercent of CPU this job got: 89%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.39', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 79808', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15900', '\tVoluntary context switches: 46', '\tInvoluntary context switches: 158', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-07_01-43-23.csv'], error []
2024-10-07 01:43:59,142 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-07 00:51:49,073 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-07 00:51:49,082 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-07 00:51:50,156 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:50,194 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:50,228 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:50,282 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:50,300 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-07 00:51:50,324 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-07 00:51:50,325 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-07 00:51:50,328 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-07 00:51:50,330 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 996"', '\tUser time (seconds): 6.66', '\tSystem time (seconds): 0.61', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.37', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80636', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16022', '\tVoluntary context switches: 56', '\tInvoluntary context switches: 246', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-07_01-43-23.csv'], error []
2024-10-07 01:44:00,513 - DEBUG - All values from powertop for client: Series([], Name: 7, dtype: object)
2024-10-07 01:44:00,513 - DEBUG - Energy client: 0.0
2024-10-07 01:44:01,787 - DEBUG - All values from powertop for server: 1       559 mW  
29     1.19 mW  
Name: 7, dtype: object
2024-10-07 01:44:01,787 - DEBUG - Energy server: 4.122998400000001
