2025-01-16 20:09:50,209 - INFO - Finished! Total sfe time: 11.003092765808105 
2025-01-16 20:09:50,209 - DEBUG - 325,server, Parsed server ram usage: 80164
2025-01-16 20:09:50,209 - DEBUG - 325,client, Parsed client ram usage: 80588
2025-01-16 20:10:10,001 - DEBUG - client all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 12 second(s) each.', '2024-12-19 00:07:37,046 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.1:61002', '2024-12-19 00:07:37,049 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.2', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.2:61001 ssl:default [Connect call failed ('192.168.1.2', 61001)]", '2024-12-19 00:07:38,117 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 00:07:38,150 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 00:07:38,257 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 00:07:38,305 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', 'By 325 mismatch.', '2024-12-19 00:07:38,322 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 00:07:38,344 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-19 00:07:38,346 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.1:61002 shutdown', 'Total bytes received: 1930', 'Total messages received: 5', '2024-12-19 00:07:38,350 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.2:61001 shutdown', 'Total bytes sent: 766', 'Total messages sent: 5', '2024-12-19 00:07:38,352 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 766', 'Total messages sent: 5', 'Total bytes received: 1930', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 1 325"', '\tUser time (seconds): 6.82', '\tSystem time (seconds): 0.73', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.69', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80796', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16074', '\tVoluntary context switches: 68', '\tInvoluntary context switches: 230', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-16_20-09-39.csv']
2025-01-16 20:10:10,001 - DEBUG - server all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 12 second(s) each.', '2024-12-19 00:08:14,491 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.2:61001', '2024-12-19 00:08:15,385 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 00:08:15,497 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 00:08:15,503 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 00:08:15,592 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', 'By 325 mismatch.', '2024-12-19 00:08:15,638 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 00:08:15,643 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-19 00:08:15,644 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.2:61001 shutdown', 'Total bytes received: 766', 'Total messages received: 5', '2024-12-19 00:08:15,648 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.1:61002 shutdown', 'Total bytes sent: 1930', 'Total messages sent: 5', '2024-12-19 00:08:15,649 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 1930', 'Total messages sent: 5', 'Total bytes received: 766', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 0 325"', '\tUser time (seconds): 6.81', '\tSystem time (seconds): 0.70', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.50', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80164', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15951', '\tVoluntary context switches: 59', '\tInvoluntary context switches: 152', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-16_20-09-39.csv']
2025-01-16 20:10:11,381 - DEBUG - All values from powertop for client: 1       516 mW  
27      909 uW  
29      796 uW  
Name: 7, dtype: object
2025-01-16 20:10:11,381 - DEBUG - Energy client: 3.8465481500000003
2025-01-16 20:10:12,690 - DEBUG - All values from powertop for server: 1       502 mW  
21     1.18 mW  
Name: 7, dtype: object
2025-01-16 20:10:12,690 - DEBUG - Energy server: 3.7285638
