2024-10-06 18:31:45,585 - INFO - Finished! Total sfe time: 10.530022859573364 
2024-10-06 18:31:45,586 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', '2024-10-06 17:39:50,208 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 17:39:51,241 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:39:51,313 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:39:51,357 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:39:51,392 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 191 mismatch.', '2024-10-06 17:39:51,438 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:39:51,442 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 17:39:51,444 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 17:39:51,447 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 17:39:51,449 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 191"', '\tUser time (seconds): 6.44', '\tSystem time (seconds): 0.70', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.22', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80412', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15906', '\tVoluntary context switches: 62', '\tInvoluntary context switches: 159', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 18:31:45,586 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', '2024-10-06 17:39:50,020 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 17:39:50,045 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 17:39:51,114 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:39:51,157 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:39:51,191 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:39:51,245 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:39:51,262 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:39:51,285 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 17:39:51,287 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 17:39:51,292 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 17:39:51,293 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 191"', '\tUser time (seconds): 6.40', '\tSystem time (seconds): 0.76', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.28', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80744', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16016', '\tVoluntary context switches: 56', '\tInvoluntary context switches: 189', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 18:31:45,586 - DEBUG - 191,server, Parsed server ram usage: {'Command being timed': '"python3 server_energy.py 0 191"', 'User time (seconds)': '6.44', 'System time (seconds)': '0.70', 'Percent of CPU this job got': '86%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.22', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80412', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '15906', 'Voluntary context switches': '62', 'Involuntary context switches': '159', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 18:31:45,586 - DEBUG - 191,client, Parsed client ram usage: {'Command being timed': '"python3 server_energy.py 1 191"', 'User time (seconds)': '6.40', 'System time (seconds)': '0.76', 'Percent of CPU this job got': '86%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.28', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80744', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '16016', 'Voluntary context switches': '56', 'Involuntary context switches': '189', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 18:32:05,222 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 17:40:01,213 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 17:40:02,113 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:40:02,194 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:40:02,230 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:40:02,266 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 191 mismatch.', '2024-10-06 17:40:02,318 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 17:40:02,322 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 17:40:02,324 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 17:40:02,327 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 17:40:02,328 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 191"', '\tUser time (seconds): 6.76', '\tSystem time (seconds): 0.74', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.46', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80452', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15909', '\tVoluntary context switches: 44', '\tInvoluntary context switches: 156', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_18-31-35.csv'], error []
2024-10-06 18:32:05,223 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 17:40:00,912 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 17:40:00,916 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 17:40:01,994 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:40:02,034 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:40:02,068 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:40:02,123 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:40:02,142 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 17:40:02,165 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 17:40:02,166 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 17:40:02,169 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 17:40:02,170 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 191"', '\tUser time (seconds): 6.81', '\tSystem time (seconds): 0.73', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.65', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80108', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16014', '\tVoluntary context switches: 41', '\tInvoluntary context switches: 174', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_18-31-35.csv'], error []
2024-10-06 18:32:06,582 - DEBUG - All values from powertop for client: 1       569 mW  
22     1.58 mW  
Name: 7, dtype: object
2024-10-06 18:32:06,582 - DEBUG - Energy client: 4.222292000000001
2024-10-06 18:32:07,908 - DEBUG - All values from powertop for server: 1       552 mW  
26     1.26 mW  
Name: 7, dtype: object
2024-10-06 18:32:07,908 - DEBUG - Energy server: 4.116254400000001
