2024-10-06 21:48:43,269 - INFO - Finished! Total sfe time: 10.325488328933716 
2024-10-06 21:48:43,269 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', '2024-10-06 20:56:48,167 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 20:56:49,047 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:49,115 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:49,158 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:49,196 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 558 success.', '2024-10-06 20:56:49,244 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:49,249 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 20:56:49,250 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 20:56:49,253 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 20:56:49,254 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 558"', '\tUser time (seconds): 6.40', '\tSystem time (seconds): 0.75', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.07', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80420', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15913', '\tVoluntary context switches: 55', '\tInvoluntary context switches: 127', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 21:48:43,270 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', '2024-10-06 20:56:47,787 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 20:56:47,794 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 20:56:48,863 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:48,904 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:48,936 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:48,995 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:49,012 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:49,035 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 20:56:49,036 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 20:56:49,039 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 20:56:49,040 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 558"', '\tUser time (seconds): 6.47', '\tSystem time (seconds): 0.68', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.25', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80860', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16026', '\tVoluntary context switches: 56', '\tInvoluntary context switches: 292', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 21:48:43,270 - DEBUG - 558,server, Parsed server ram usage: {'Command being timed': '"python3 server_energy.py 0 558"', 'User time (seconds)': '6.40', 'System time (seconds)': '0.75', 'Percent of CPU this job got': '88%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.07', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80420', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '15913', 'Voluntary context switches': '55', 'Involuntary context switches': '127', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 21:48:43,270 - DEBUG - 558,client, Parsed client ram usage: {'Command being timed': '"python3 server_energy.py 1 558"', 'User time (seconds)': '6.47', 'System time (seconds)': '0.68', 'Percent of CPU this job got': '86%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.25', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80860', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '16026', 'Voluntary context switches': '56', 'Involuntary context switches': '292', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 21:49:01,719 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 20:56:58,800 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 20:56:59,730 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:59,807 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:59,845 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:59,881 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 558 success.', '2024-10-06 20:56:59,930 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 20:56:59,935 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 20:56:59,936 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 20:56:59,940 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 20:56:59,942 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 558"', '\tUser time (seconds): 6.71', '\tSystem time (seconds): 0.79', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.50', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80400', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15906', '\tVoluntary context switches: 45', '\tInvoluntary context switches: 158', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_21-48-32.csv'], error []
2024-10-06 21:49:01,719 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 20:56:58,472 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 20:56:58,478 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 20:56:59,552 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:59,591 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:59,625 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:59,679 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:59,698 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 20:56:59,722 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 20:56:59,724 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 20:56:59,729 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 20:56:59,730 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 558"', '\tUser time (seconds): 6.74', '\tSystem time (seconds): 0.77', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.63', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80728', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16018', '\tVoluntary context switches: 49', '\tInvoluntary context switches: 262', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_21-48-32.csv'], error []
2024-10-06 21:49:03,236 - DEBUG - All values from powertop for client: 1       568 mW  
28     1.24 mW  
Name: 7, dtype: object
2024-10-06 21:49:03,236 - DEBUG - Energy client: 4.2522228
2024-10-06 21:49:04,564 - DEBUG - All values from powertop for server: 1      563 mW  
9     8.35 mW  
Name: 7, dtype: object
2024-10-06 21:49:04,564 - DEBUG - Energy server: 4.22799
